services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NewStrongPassword1234
      POSTGRES_DB: mydatabase
      PGDATA: /var/lib/postgresql/data
    networks:
      - app-network

  log:
    build: ./log
    container_name: log
    restart: always
    depends_on:
      - db
    networks:
      - app-network
      
  # quizz:
  #   build: ./quizz
  #   container_name: quizz
  #   restart: always
  #   depends_on:
  #     - db
  #   networks:
  #     - app-network

  # forum:
  #   build: ./forum
  #   container_name: forum
  #   restart: always
  #   depends_on:
  #     - db
  #   networks:
  #     - app-network

  # admin:
  #   build: ./admin
  #   container_name: admin
  #   restart: always
  #   depends_on:
  #     - db
  #   networks:
  #     - app-network

volumes:
  caddy_data:
  caddy_config:

networks:
  app-network:
    driver: bridge
